[workspace]
channels = ["conda-forge"]
name = "open-data-projects"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks.app]
description = "Run Streamlit app"
cmd = "streamlit run app.py"

[tasks.start]
depends-on = ["app"]

[dependencies]
streamlit = ">=1.51.0,<2"
pandas = ">=2.3.3,<3"
